export const bigMultipliers = [
    {
        "defenderType": "normal",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 1 },
            { "attackerType": "fighting", "multiplier": 2 },
            { "attackerType": "flying",   "multiplier": 1 },
            { "attackerType": "poison",   "multiplier": 1 },
            { "attackerType": "ground",   "multiplier": 1 },
            { "attackerType": "rock",     "multiplier": 1 },
            { "attackerType": "bug",      "multiplier": 1 },
            { "attackerType": "ghost",    "multiplier": 0 },
            { "attackerType": "steel",    "multiplier": 1 },
            { "attackerType": "fire",     "multiplier": 1 },
            { "attackerType": "water",    "multiplier": 1 },
            { "attackerType": "grass",    "multiplier": 1 },
            { "attackerType": "electric", "multiplier": 1 },
            { "attackerType": "psychic",  "multiplier": 1 },
            { "attackerType": "ice",      "multiplier": 1 },
            { "attackerType": "dragon",   "multiplier": 1 },
            { "attackerType": "dark",     "multiplier": 1 },
            { "attackerType": "fairy",    "multiplier": 1 }
        ]
    },
    {
        "defenderType": "fighting",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 1 },
            { "attackerType": "fighting", "multiplier": 1 },
            { "attackerType": "flying",   "multiplier": 2 },
            { "attackerType": "poison",   "multiplier": 1 },
            { "attackerType": "ground",   "multiplier": 1 },
            { "attackerType": "rock",     "multiplier": 0.5 },
            { "attackerType": "bug",      "multiplier": 0.5 },
            { "attackerType": "ghost",    "multiplier": 1 },
            { "attackerType": "steel",    "multiplier": 1 },
            { "attackerType": "fire",     "multiplier": 1 },
            { "attackerType": "water",    "multiplier": 1 },
            { "attackerType": "grass",    "multiplier": 1 },
            { "attackerType": "electric", "multiplier": 1 },
            { "attackerType": "psychic",  "multiplier": 2 },
            { "attackerType": "ice",      "multiplier": 1 },
            { "attackerType": "dragon",   "multiplier": 1 },
            { "attackerType": "dark",     "multiplier": 0.5 },
            { "attackerType": "fairy",    "multiplier": 2 }
        ]
    },
    {
        "defenderType": "flying",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 1 },
            { "attackerType": "fighting", "multiplier": 0.5 },
            { "attackerType": "flying",   "multiplier": 1 },
            { "attackerType": "poison",   "multiplier": 1 },
            { "attackerType": "ground",   "multiplier": 0 },
            { "attackerType": "rock",     "multiplier": 2 },
            { "attackerType": "bug",      "multiplier": 0.5 },
            { "attackerType": "ghost",    "multiplier": 1 },
            { "attackerType": "steel",    "multiplier": 0.5 },
            { "attackerType": "fire",     "multiplier": 1 },
            { "attackerType": "water",    "multiplier": 1 },
            { "attackerType": "grass",    "multiplier": 0.5 },
            { "attackerType": "electric", "multiplier": 2 },
            { "attackerType": "psychic",  "multiplier": 1 },
            { "attackerType": "ice",      "multiplier": 2 },
            { "attackerType": "dragon",   "multiplier": 1 },
            { "attackerType": "dark",     "multiplier": 1 },
            { "attackerType": "fairy",    "multiplier": 1 }
        ]
    },
    {
        "defenderType": "poison",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 1 },
            { "attackerType": "fighting", "multiplier": 0.5 },
            { "attackerType": "flying",   "multiplier": 1 },
            { "attackerType": "poison",   "multiplier": 0.5 },
            { "attackerType": "ground",   "multiplier": 2 },
            { "attackerType": "rock",     "multiplier": 1 },
            { "attackerType": "bug",      "multiplier": 0.5 },
            { "attackerType": "ghost",    "multiplier": 1 },
            { "attackerType": "steel",    "multiplier": 1 },
            { "attackerType": "fire",     "multiplier": 1 },
            { "attackerType": "water",    "multiplier": 1 },
            { "attackerType": "grass",    "multiplier": 0.5 },
            { "attackerType": "electric", "multiplier": 1 },
            { "attackerType": "psychic",  "multiplier": 2 },
            { "attackerType": "ice",      "multiplier": 1 },
            { "attackerType": "dragon",   "multiplier": 1 },
            { "attackerType": "dark",     "multiplier": 1 },
            { "attackerType": "fairy",    "multiplier": 0.5 }
        ]
    },
    {
        "defenderType": "ground",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 1 },
            { "attackerType": "fighting", "multiplier": 1 },
            { "attackerType": "flying",   "multiplier": 1 },
            { "attackerType": "poison",   "multiplier": 0.5 },
            { "attackerType": "ground",   "multiplier": 1 },
            { "attackerType": "rock",     "multiplier": 0.5 },
            { "attackerType": "bug",      "multiplier": 1 },
            { "attackerType": "ghost",    "multiplier": 1 },
            { "attackerType": "steel",    "multiplier": 1 },
            { "attackerType": "fire",     "multiplier": 1 },
            { "attackerType": "water",    "multiplier": 2 },
            { "attackerType": "grass",    "multiplier": 2 },
            { "attackerType": "electric", "multiplier": 0 },
            { "attackerType": "psychic",  "multiplier": 1 },
            { "attackerType": "ice",      "multiplier": 2 },
            { "attackerType": "dragon",   "multiplier": 1 },
            { "attackerType": "dark",     "multiplier": 1 },
            { "attackerType": "fairy",    "multiplier": 1 }
        ]
    },
    {
        "defenderType": "rock",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 0.5 },
            { "attackerType": "fighting", "multiplier": 2 },
            { "attackerType": "flying",   "multiplier": 0.5 },
            { "attackerType": "poison",   "multiplier": 0.5 },
            { "attackerType": "ground",   "multiplier": 2 },
            { "attackerType": "rock",     "multiplier": 1 },
            { "attackerType": "bug",      "multiplier": 1 },
            { "attackerType": "ghost",    "multiplier": 1 },
            { "attackerType": "steel",    "multiplier": 2 },
            { "attackerType": "fire",     "multiplier": 0.5 },
            { "attackerType": "water",    "multiplier": 2 },
            { "attackerType": "grass",    "multiplier": 2 },
            { "attackerType": "electric", "multiplier": 1 },
            { "attackerType": "psychic",  "multiplier": 1 },
            { "attackerType": "ice",      "multiplier": 1 },
            { "attackerType": "dragon",   "multiplier": 1 },
            { "attackerType": "dark",     "multiplier": 1 },
            { "attackerType": "fairy",    "multiplier": 1 }
        ]
    },
    {
        "defenderType": "bug",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 1 },
            { "attackerType": "fighting", "multiplier": 0.5 },
            { "attackerType": "flying",   "multiplier": 2 },
            { "attackerType": "poison",   "multiplier": 1 },
            { "attackerType": "ground",   "multiplier": 0.5 },
            { "attackerType": "rock",     "multiplier": 2 },
            { "attackerType": "bug",      "multiplier": 1 },
            { "attackerType": "ghost",    "multiplier": 1 },
            { "attackerType": "steel",    "multiplier": 1 },
            { "attackerType": "fire",     "multiplier": 2 },
            { "attackerType": "water",    "multiplier": 1 },
            { "attackerType": "grass",    "multiplier": 0.5 },
            { "attackerType": "electric", "multiplier": 1 },
            { "attackerType": "psychic",  "multiplier": 1 },
            { "attackerType": "ice",      "multiplier": 1 },
            { "attackerType": "dragon",   "multiplier": 1 },
            { "attackerType": "dark",     "multiplier": 1 },
            { "attackerType": "fairy",    "multiplier": 1 }
        ]
    },
    {
        "defenderType": "ghost",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 0 },
            { "attackerType": "fighting", "multiplier": 0 },
            { "attackerType": "flying",   "multiplier": 1 },
            { "attackerType": "poison",   "multiplier": 0.5 },
            { "attackerType": "ground",   "multiplier": 1 },
            { "attackerType": "rock",     "multiplier": 1 },
            { "attackerType": "bug",      "multiplier": 0.5 },
            { "attackerType": "ghost",    "multiplier": 2 },
            { "attackerType": "steel",    "multiplier": 1 },
            { "attackerType": "fire",     "multiplier": 1 },
            { "attackerType": "water",    "multiplier": 1 },
            { "attackerType": "grass",    "multiplier": 1 },
            { "attackerType": "electric", "multiplier": 1 },
            { "attackerType": "psychic",  "multiplier": 1 },
            { "attackerType": "ice",      "multiplier": 1 },
            { "attackerType": "dragon",   "multiplier": 1 },
            { "attackerType": "dark",     "multiplier": 2 },
            { "attackerType": "fairy",    "multiplier": 1 }
        ]
    },
    {
        "defenderType": "steel",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 0.5 },
            { "attackerType": "fighting", "multiplier": 2 },
            { "attackerType": "flying",   "multiplier": 0.5 },
            { "attackerType": "poison",   "multiplier": 0 },
            { "attackerType": "ground",   "multiplier": 2 },
            { "attackerType": "rock",     "multiplier": 0.5 },
            { "attackerType": "bug",      "multiplier": 0.5 },
            { "attackerType": "ghost",    "multiplier": 1 },
            { "attackerType": "steel",    "multiplier": 0.5 },
            { "attackerType": "fire",     "multiplier": 2 },
            { "attackerType": "water",    "multiplier": 1 },
            { "attackerType": "grass",    "multiplier": 0.5 },
            { "attackerType": "electric", "multiplier": 1 },
            { "attackerType": "psychic",  "multiplier": 0.5 },
            { "attackerType": "ice",      "multiplier": 0.5 },
            { "attackerType": "dragon",   "multiplier": 0.5 },
            { "attackerType": "dark",     "multiplier": 1 },
            { "attackerType": "fairy",    "multiplier": 0.5 }
        ]
    },
    {
        "defenderType": "fire",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 1 },
            { "attackerType": "fighting", "multiplier": 1 },
            { "attackerType": "flying",   "multiplier": 1 },
            { "attackerType": "poison",   "multiplier": 1 },
            { "attackerType": "ground",   "multiplier": 2 },
            { "attackerType": "rock",     "multiplier": 2 },
            { "attackerType": "bug",      "multiplier": 0.5 },
            { "attackerType": "ghost",    "multiplier": 1 },
            { "attackerType": "steel",    "multiplier": 0.5 },
            { "attackerType": "fire",     "multiplier": 0.5 },
            { "attackerType": "water",    "multiplier": 2 },
            { "attackerType": "grass",    "multiplier": 0.5 },
            { "attackerType": "electric", "multiplier": 1 },
            { "attackerType": "psychic",  "multiplier": 1 },
            { "attackerType": "ice",      "multiplier": 0.5 },
            { "attackerType": "dragon",   "multiplier": 1 },
            { "attackerType": "dark",     "multiplier": 1 },
            { "attackerType": "fairy",    "multiplier": 0.5 }
        ]
    },
    {
        "defenderType": "water",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 1 },
            { "attackerType": "fighting", "multiplier": 1 },
            { "attackerType": "flying",   "multiplier": 1 },
            { "attackerType": "poison",   "multiplier": 1 },
            { "attackerType": "ground",   "multiplier": 1 },
            { "attackerType": "rock",     "multiplier": 1 },
            { "attackerType": "bug",      "multiplier": 1 },
            { "attackerType": "ghost",    "multiplier": 1 },
            { "attackerType": "steel",    "multiplier": 0.5 },
            { "attackerType": "fire",     "multiplier": 0.5 },
            { "attackerType": "water",    "multiplier": 0.5 },
            { "attackerType": "grass",    "multiplier": 2 },
            { "attackerType": "electric", "multiplier": 2 },
            { "attackerType": "psychic",  "multiplier": 1 },
            { "attackerType": "ice",      "multiplier": 0.5 },
            { "attackerType": "dragon",   "multiplier": 1 },
            { "attackerType": "dark",     "multiplier": 1 },
            { "attackerType": "fairy",    "multiplier": 1 }
        ]
    },
    {
        "defenderType": "grass",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 1 },
            { "attackerType": "fighting", "multiplier": 1 },
            { "attackerType": "flying",   "multiplier": 2 },
            { "attackerType": "poison",   "multiplier": 2 },
            { "attackerType": "ground",   "multiplier": 0.5 },
            { "attackerType": "rock",     "multiplier": 1 },
            { "attackerType": "bug",      "multiplier": 2 },
            { "attackerType": "ghost",    "multiplier": 1 },
            { "attackerType": "steel",    "multiplier": 1 },
            { "attackerType": "fire",     "multiplier": 2 },
            { "attackerType": "water",    "multiplier": 0.5 },
            { "attackerType": "grass",    "multiplier": 0.5 },
            { "attackerType": "electric", "multiplier": 0.5 },
            { "attackerType": "psychic",  "multiplier": 1 },
            { "attackerType": "ice",      "multiplier": 2 },
            { "attackerType": "dragon",   "multiplier": 1 },
            { "attackerType": "dark",     "multiplier": 1 },
            { "attackerType": "fairy",    "multiplier": 1 }
        ]
    },
    {
        "defenderType": "electric",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 1 },
            { "attackerType": "fighting", "multiplier": 1 },
            { "attackerType": "flying",   "multiplier": 0.5 },
            { "attackerType": "poison",   "multiplier": 1 },
            { "attackerType": "ground",   "multiplier": 2 },
            { "attackerType": "rock",     "multiplier": 1 },
            { "attackerType": "bug",      "multiplier": 1 },
            { "attackerType": "ghost",    "multiplier": 1 },
            { "attackerType": "steel",    "multiplier": 0.5 },
            { "attackerType": "fire",     "multiplier": 1 },
            { "attackerType": "water",    "multiplier": 1 },
            { "attackerType": "grass",    "multiplier": 1 },
            { "attackerType": "electric", "multiplier": 0.5 },
            { "attackerType": "psychic",  "multiplier": 1 },
            { "attackerType": "ice",      "multiplier": 1 },
            { "attackerType": "dragon",   "multiplier": 1 },
            { "attackerType": "dark",     "multiplier": 1 },
            { "attackerType": "fairy",    "multiplier": 1 }
        ]
    },
    {
        "defenderType": "psychic",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 1 },
            { "attackerType": "fighting", "multiplier": 0.5 },
            { "attackerType": "flying",   "multiplier": 1 },
            { "attackerType": "poison",   "multiplier": 1 },
            { "attackerType": "ground",   "multiplier": 1 },
            { "attackerType": "rock",     "multiplier": 1 },
            { "attackerType": "bug",      "multiplier": 2 },
            { "attackerType": "ghost",    "multiplier": 2 },
            { "attackerType": "steel",    "multiplier": 1 },
            { "attackerType": "fire",     "multiplier": 1 },
            { "attackerType": "water",    "multiplier": 1 },
            { "attackerType": "grass",    "multiplier": 1 },
            { "attackerType": "electric", "multiplier": 1 },
            { "attackerType": "psychic",  "multiplier": 0.5 },
            { "attackerType": "ice",      "multiplier": 1 },
            { "attackerType": "dragon",   "multiplier": 1 },
            { "attackerType": "dark",     "multiplier": 2 },
            { "attackerType": "fairy",    "multiplier": 1 }
        ]
    },
    {
        "defenderType": "ice",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 1 },
            { "attackerType": "fighting", "multiplier": 2 },
            { "attackerType": "flying",   "multiplier": 1 },
            { "attackerType": "poison",   "multiplier": 1 },
            { "attackerType": "ground",   "multiplier": 1 },
            { "attackerType": "rock",     "multiplier": 2 },
            { "attackerType": "bug",      "multiplier": 1 },
            { "attackerType": "ghost",    "multiplier": 1 },
            { "attackerType": "steel",    "multiplier": 2 },
            { "attackerType": "fire",     "multiplier": 2 },
            { "attackerType": "water",    "multiplier": 1 },
            { "attackerType": "grass",    "multiplier": 1 },
            { "attackerType": "electric", "multiplier": 1 },
            { "attackerType": "psychic",  "multiplier": 1 },
            { "attackerType": "ice",      "multiplier": 0.5 },
            { "attackerType": "dragon",   "multiplier": 1 },
            { "attackerType": "dark",     "multiplier": 1 },
            { "attackerType": "fairy",    "multiplier": 1 }
        ]
    },
    {
        "defenderType": "dragon",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 1 },
            { "attackerType": "fighting", "multiplier": 1 },
            { "attackerType": "flying",   "multiplier": 1 },
            { "attackerType": "poison",   "multiplier": 1 },
            { "attackerType": "ground",   "multiplier": 1 },
            { "attackerType": "rock",     "multiplier": 1 },
            { "attackerType": "bug",      "multiplier": 1 },
            { "attackerType": "ghost",    "multiplier": 1 },
            { "attackerType": "steel",    "multiplier": 1 },
            { "attackerType": "fire",     "multiplier": 0.5 },
            { "attackerType": "water",    "multiplier": 0.5 },
            { "attackerType": "grass",    "multiplier": 0.5 },
            { "attackerType": "electric", "multiplier": 0.5 },
            { "attackerType": "psychic",  "multiplier": 1 },
            { "attackerType": "ice",      "multiplier": 2 },
            { "attackerType": "dragon",   "multiplier": 2 },
            { "attackerType": "dark",     "multiplier": 1 },
            { "attackerType": "fairy",    "multiplier": 2 }
        ]
    },
    {
        "defenderType": "dark",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 1 },
            { "attackerType": "fighting", "multiplier": 2 },
            { "attackerType": "flying",   "multiplier": 1 },
            { "attackerType": "poison",   "multiplier": 1 },
            { "attackerType": "ground",   "multiplier": 1 },
            { "attackerType": "rock",     "multiplier": 1 },
            { "attackerType": "bug",      "multiplier": 2 },
            { "attackerType": "ghost",    "multiplier": 0.5 },
            { "attackerType": "steel",    "multiplier": 1 },
            { "attackerType": "fire",     "multiplier": 1 },
            { "attackerType": "water",    "multiplier": 1 },
            { "attackerType": "grass",    "multiplier": 1 },
            { "attackerType": "electric", "multiplier": 1 },
            { "attackerType": "psychic",  "multiplier": 0 },
            { "attackerType": "ice",      "multiplier": 1 },
            { "attackerType": "dragon",   "multiplier": 1 },
            { "attackerType": "dark",     "multiplier": 0.5 },
            { "attackerType": "fairy",    "multiplier": 2 }
        ]
    },
    {
        "defenderType": "fairy",
        "attackerFactors": [
            { "attackerType": "normal",   "multiplier": 1 },
            { "attackerType": "fighting", "multiplier": 0.5 },
            { "attackerType": "flying",   "multiplier": 1 },
            { "attackerType": "poison",   "multiplier": 2 },
            { "attackerType": "ground",   "multiplier": 1 },
            { "attackerType": "rock",     "multiplier": 1 },
            { "attackerType": "bug",      "multiplier": 0.5 },
            { "attackerType": "ghost",    "multiplier": 1 },
            { "attackerType": "steel",    "multiplier": 2 },
            { "attackerType": "fire",     "multiplier": 1 },
            { "attackerType": "water",    "multiplier": 1 },
            { "attackerType": "grass",    "multiplier": 1 },
            { "attackerType": "electric", "multiplier": 1 },
            { "attackerType": "psychic",  "multiplier": 1 },
            { "attackerType": "ice",      "multiplier": 1 },
            { "attackerType": "dragon",   "multiplier": 0 },
            { "attackerType": "dark",     "multiplier": 0.5 },
            { "attackerType": "fairy",    "multiplier": 1 }
        ]
    }
]
