export const bigMultipliers = [
    {
        "defenderType": "normal",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 1 },
            { "attackerType": "fighting", "multipliers": 2 },
            { "attackerType": "flying",   "multipliers": 1 },
            { "attackerType": "poison",   "multipliers": 1 },
            { "attackerType": "ground",   "multipliers": 1 },
            { "attackerType": "rock",     "multipliers": 1 },
            { "attackerType": "bug",      "multipliers": 1 },
            { "attackerType": "ghost",    "multipliers": 0 },
            { "attackerType": "steel",    "multipliers": 1 },
            { "attackerType": "fire",     "multipliers": 1 },
            { "attackerType": "water",    "multipliers": 1 },
            { "attackerType": "grass",    "multipliers": 1 },
            { "attackerType": "electric", "multipliers": 1 },
            { "attackerType": "psychic",  "multipliers": 1 },
            { "attackerType": "ice",      "multipliers": 1 },
            { "attackerType": "dragon",   "multipliers": 1 },
            { "attackerType": "dark",     "multipliers": 1 },
            { "attackerType": "fairy",    "multipliers": 1 }
        ]
    },
    {
        "defenderType": "fighting",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 1 },
            { "attackerType": "fighting", "multipliers": 1 },
            { "attackerType": "flying",   "multipliers": 2 },
            { "attackerType": "poison",   "multipliers": 1 },
            { "attackerType": "ground",   "multipliers": 1 },
            { "attackerType": "rock",     "multipliers": 0.5 },
            { "attackerType": "bug",      "multipliers": 0.5 },
            { "attackerType": "ghost",    "multipliers": 1 },
            { "attackerType": "steel",    "multipliers": 1 },
            { "attackerType": "fire",     "multipliers": 1 },
            { "attackerType": "water",    "multipliers": 1 },
            { "attackerType": "grass",    "multipliers": 1 },
            { "attackerType": "electric", "multipliers": 1 },
            { "attackerType": "psychic",  "multipliers": 2 },
            { "attackerType": "ice",      "multipliers": 1 },
            { "attackerType": "dragon",   "multipliers": 1 },
            { "attackerType": "dark",     "multipliers": 0.5 },
            { "attackerType": "fairy",    "multipliers": 2 }
        ]
    },
    {
        "defenderType": "flying",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 1 },
            { "attackerType": "fighting", "multipliers": 0.5 },
            { "attackerType": "flying",   "multipliers": 1 },
            { "attackerType": "poison",   "multipliers": 1 },
            { "attackerType": "ground",   "multipliers": 0 },
            { "attackerType": "rock",     "multipliers": 2 },
            { "attackerType": "bug",      "multipliers": 0.5 },
            { "attackerType": "ghost",    "multipliers": 1 },
            { "attackerType": "steel",    "multipliers": 0.5 },
            { "attackerType": "fire",     "multipliers": 1 },
            { "attackerType": "water",    "multipliers": 1 },
            { "attackerType": "grass",    "multipliers": 0.5 },
            { "attackerType": "electric", "multipliers": 2 },
            { "attackerType": "psychic",  "multipliers": 1 },
            { "attackerType": "ice",      "multipliers": 2 },
            { "attackerType": "dragon",   "multipliers": 1 },
            { "attackerType": "dark",     "multipliers": 1 },
            { "attackerType": "fairy",    "multipliers": 1 }
        ]
    },
    {
        "defenderType": "poison",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 1 },
            { "attackerType": "fighting", "multipliers": 0.5 },
            { "attackerType": "flying",   "multipliers": 1 },
            { "attackerType": "poison",   "multipliers": 0.5 },
            { "attackerType": "ground",   "multipliers": 2 },
            { "attackerType": "rock",     "multipliers": 1 },
            { "attackerType": "bug",      "multipliers": 0.5 },
            { "attackerType": "ghost",    "multipliers": 1 },
            { "attackerType": "steel",    "multipliers": 1 },
            { "attackerType": "fire",     "multipliers": 1 },
            { "attackerType": "water",    "multipliers": 1 },
            { "attackerType": "grass",    "multipliers": 0.5 },
            { "attackerType": "electric", "multipliers": 1 },
            { "attackerType": "psychic",  "multipliers": 2 },
            { "attackerType": "ice",      "multipliers": 1 },
            { "attackerType": "dragon",   "multipliers": 1 },
            { "attackerType": "dark",     "multipliers": 1 },
            { "attackerType": "fairy",    "multipliers": 0.5 }
        ]
    },
    {
        "defenderType": "ground",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 1 },
            { "attackerType": "fighting", "multipliers": 1 },
            { "attackerType": "flying",   "multipliers": 1 },
            { "attackerType": "poison",   "multipliers": 0.5 },
            { "attackerType": "ground",   "multipliers": 1 },
            { "attackerType": "rock",     "multipliers": 0.5 },
            { "attackerType": "bug",      "multipliers": 1 },
            { "attackerType": "ghost",    "multipliers": 1 },
            { "attackerType": "steel",    "multipliers": 1 },
            { "attackerType": "fire",     "multipliers": 1 },
            { "attackerType": "water",    "multipliers": 2 },
            { "attackerType": "grass",    "multipliers": 2 },
            { "attackerType": "electric", "multipliers": 0 },
            { "attackerType": "psychic",  "multipliers": 1 },
            { "attackerType": "ice",      "multipliers": 2 },
            { "attackerType": "dragon",   "multipliers": 1 },
            { "attackerType": "dark",     "multipliers": 1 },
            { "attackerType": "fairy",    "multipliers": 1 }
        ]
    },
    {
        "defenderType": "rock",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 0.5 },
            { "attackerType": "fighting", "multipliers": 2 },
            { "attackerType": "flying",   "multipliers": 0.5 },
            { "attackerType": "poison",   "multipliers": 0.5 },
            { "attackerType": "ground",   "multipliers": 2 },
            { "attackerType": "rock",     "multipliers": 1 },
            { "attackerType": "bug",      "multipliers": 1 },
            { "attackerType": "ghost",    "multipliers": 1 },
            { "attackerType": "steel",    "multipliers": 2 },
            { "attackerType": "fire",     "multipliers": 0.5 },
            { "attackerType": "water",    "multipliers": 2 },
            { "attackerType": "grass",    "multipliers": 2 },
            { "attackerType": "electric", "multipliers": 1 },
            { "attackerType": "psychic",  "multipliers": 1 },
            { "attackerType": "ice",      "multipliers": 1 },
            { "attackerType": "dragon",   "multipliers": 1 },
            { "attackerType": "dark",     "multipliers": 1 },
            { "attackerType": "fairy",    "multipliers": 1 }
        ]
    },
    {
        "defenderType": "bug",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 1 },
            { "attackerType": "fighting", "multipliers": 0.5 },
            { "attackerType": "flying",   "multipliers": 2 },
            { "attackerType": "poison",   "multipliers": 1 },
            { "attackerType": "ground",   "multipliers": 0.5 },
            { "attackerType": "rock",     "multipliers": 2 },
            { "attackerType": "bug",      "multipliers": 1 },
            { "attackerType": "ghost",    "multipliers": 1 },
            { "attackerType": "steel",    "multipliers": 1 },
            { "attackerType": "fire",     "multipliers": 2 },
            { "attackerType": "water",    "multipliers": 1 },
            { "attackerType": "grass",    "multipliers": 0.5 },
            { "attackerType": "electric", "multipliers": 1 },
            { "attackerType": "psychic",  "multipliers": 1 },
            { "attackerType": "ice",      "multipliers": 1 },
            { "attackerType": "dragon",   "multipliers": 1 },
            { "attackerType": "dark",     "multipliers": 1 },
            { "attackerType": "fairy",    "multipliers": 1 }
        ]
    },
    {
        "defenderType": "ghost",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 0 },
            { "attackerType": "fighting", "multipliers": 0 },
            { "attackerType": "flying",   "multipliers": 1 },
            { "attackerType": "poison",   "multipliers": 0.5 },
            { "attackerType": "ground",   "multipliers": 1 },
            { "attackerType": "rock",     "multipliers": 1 },
            { "attackerType": "bug",      "multipliers": 0.5 },
            { "attackerType": "ghost",    "multipliers": 2 },
            { "attackerType": "steel",    "multipliers": 1 },
            { "attackerType": "fire",     "multipliers": 1 },
            { "attackerType": "water",    "multipliers": 1 },
            { "attackerType": "grass",    "multipliers": 1 },
            { "attackerType": "electric", "multipliers": 1 },
            { "attackerType": "psychic",  "multipliers": 1 },
            { "attackerType": "ice",      "multipliers": 1 },
            { "attackerType": "dragon",   "multipliers": 1 },
            { "attackerType": "dark",     "multipliers": 2 },
            { "attackerType": "fairy",    "multipliers": 1 }
        ]
    },
    {
        "defenderType": "steel",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 0.5 },
            { "attackerType": "fighting", "multipliers": 2 },
            { "attackerType": "flying",   "multipliers": 0.5 },
            { "attackerType": "poison",   "multipliers": 0 },
            { "attackerType": "ground",   "multipliers": 2 },
            { "attackerType": "rock",     "multipliers": 0.5 },
            { "attackerType": "bug",      "multipliers": 0.5 },
            { "attackerType": "ghost",    "multipliers": 1 },
            { "attackerType": "steel",    "multipliers": 0.5 },
            { "attackerType": "fire",     "multipliers": 2 },
            { "attackerType": "water",    "multipliers": 1 },
            { "attackerType": "grass",    "multipliers": 0.5 },
            { "attackerType": "electric", "multipliers": 1 },
            { "attackerType": "psychic",  "multipliers": 0.5 },
            { "attackerType": "ice",      "multipliers": 0.5 },
            { "attackerType": "dragon",   "multipliers": 0.5 },
            { "attackerType": "dark",     "multipliers": 1 },
            { "attackerType": "fairy",    "multipliers": 0.5 }
        ]
    },
    {
        "defenderType": "fire",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 1 },
            { "attackerType": "fighting", "multipliers": 1 },
            { "attackerType": "flying",   "multipliers": 1 },
            { "attackerType": "poison",   "multipliers": 1 },
            { "attackerType": "ground",   "multipliers": 2 },
            { "attackerType": "rock",     "multipliers": 2 },
            { "attackerType": "bug",      "multipliers": 0.5 },
            { "attackerType": "ghost",    "multipliers": 1 },
            { "attackerType": "steel",    "multipliers": 0.5 },
            { "attackerType": "fire",     "multipliers": 0.5 },
            { "attackerType": "water",    "multipliers": 2 },
            { "attackerType": "grass",    "multipliers": 0.5 },
            { "attackerType": "electric", "multipliers": 1 },
            { "attackerType": "psychic",  "multipliers": 1 },
            { "attackerType": "ice",      "multipliers": 0.5 },
            { "attackerType": "dragon",   "multipliers": 1 },
            { "attackerType": "dark",     "multipliers": 1 },
            { "attackerType": "fairy",    "multipliers": 0.5 }
        ]
    },
    {
        "defenderType": "water",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 1 },
            { "attackerType": "fighting", "multipliers": 1 },
            { "attackerType": "flying",   "multipliers": 1 },
            { "attackerType": "poison",   "multipliers": 1 },
            { "attackerType": "ground",   "multipliers": 1 },
            { "attackerType": "rock",     "multipliers": 1 },
            { "attackerType": "bug",      "multipliers": 1 },
            { "attackerType": "ghost",    "multipliers": 1 },
            { "attackerType": "steel",    "multipliers": 0.5 },
            { "attackerType": "fire",     "multipliers": 0.5 },
            { "attackerType": "water",    "multipliers": 0.5 },
            { "attackerType": "grass",    "multipliers": 2 },
            { "attackerType": "electric", "multipliers": 2 },
            { "attackerType": "psychic",  "multipliers": 1 },
            { "attackerType": "ice",      "multipliers": 0.5 },
            { "attackerType": "dragon",   "multipliers": 1 },
            { "attackerType": "dark",     "multipliers": 1 },
            { "attackerType": "fairy",    "multipliers": 1 }
        ]
    },
    {
        "defenderType": "grass",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 1 },
            { "attackerType": "fighting", "multipliers": 1 },
            { "attackerType": "flying",   "multipliers": 2 },
            { "attackerType": "poison",   "multipliers": 2 },
            { "attackerType": "ground",   "multipliers": 0.5 },
            { "attackerType": "rock",     "multipliers": 1 },
            { "attackerType": "bug",      "multipliers": 2 },
            { "attackerType": "ghost",    "multipliers": 1 },
            { "attackerType": "steel",    "multipliers": 1 },
            { "attackerType": "fire",     "multipliers": 2 },
            { "attackerType": "water",    "multipliers": 0.5 },
            { "attackerType": "grass",    "multipliers": 0.5 },
            { "attackerType": "electric", "multipliers": 0.5 },
            { "attackerType": "psychic",  "multipliers": 1 },
            { "attackerType": "ice",      "multipliers": 2 },
            { "attackerType": "dragon",   "multipliers": 1 },
            { "attackerType": "dark",     "multipliers": 1 },
            { "attackerType": "fairy",    "multipliers": 1 }
        ]
    },
    {
        "defenderType": "electric",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 1 },
            { "attackerType": "fighting", "multipliers": 1 },
            { "attackerType": "flying",   "multipliers": 0.5 },
            { "attackerType": "poison",   "multipliers": 1 },
            { "attackerType": "ground",   "multipliers": 2 },
            { "attackerType": "rock",     "multipliers": 1 },
            { "attackerType": "bug",      "multipliers": 1 },
            { "attackerType": "ghost",    "multipliers": 1 },
            { "attackerType": "steel",    "multipliers": 0.5 },
            { "attackerType": "fire",     "multipliers": 1 },
            { "attackerType": "water",    "multipliers": 1 },
            { "attackerType": "grass",    "multipliers": 1 },
            { "attackerType": "electric", "multipliers": 0.5 },
            { "attackerType": "psychic",  "multipliers": 1 },
            { "attackerType": "ice",      "multipliers": 1 },
            { "attackerType": "dragon",   "multipliers": 1 },
            { "attackerType": "dark",     "multipliers": 1 },
            { "attackerType": "fairy",    "multipliers": 1 }
        ]
    },
    {
        "defenderType": "psychic",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 1 },
            { "attackerType": "fighting", "multipliers": 0.5 },
            { "attackerType": "flying",   "multipliers": 1 },
            { "attackerType": "poison",   "multipliers": 1 },
            { "attackerType": "ground",   "multipliers": 1 },
            { "attackerType": "rock",     "multipliers": 1 },
            { "attackerType": "bug",      "multipliers": 2 },
            { "attackerType": "ghost",    "multipliers": 2 },
            { "attackerType": "steel",    "multipliers": 1 },
            { "attackerType": "fire",     "multipliers": 1 },
            { "attackerType": "water",    "multipliers": 1 },
            { "attackerType": "grass",    "multipliers": 1 },
            { "attackerType": "electric", "multipliers": 1 },
            { "attackerType": "psychic",  "multipliers": 0.5 },
            { "attackerType": "ice",      "multipliers": 1 },
            { "attackerType": "dragon",   "multipliers": 1 },
            { "attackerType": "dark",     "multipliers": 2 },
            { "attackerType": "fairy",    "multipliers": 1 }
        ]
    },
    {
        "defenderType": "ice",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 1 },
            { "attackerType": "fighting", "multipliers": 2 },
            { "attackerType": "flying",   "multipliers": 1 },
            { "attackerType": "poison",   "multipliers": 1 },
            { "attackerType": "ground",   "multipliers": 1 },
            { "attackerType": "rock",     "multipliers": 2 },
            { "attackerType": "bug",      "multipliers": 1 },
            { "attackerType": "ghost",    "multipliers": 1 },
            { "attackerType": "steel",    "multipliers": 2 },
            { "attackerType": "fire",     "multipliers": 2 },
            { "attackerType": "water",    "multipliers": 1 },
            { "attackerType": "grass",    "multipliers": 1 },
            { "attackerType": "electric", "multipliers": 1 },
            { "attackerType": "psychic",  "multipliers": 1 },
            { "attackerType": "ice",      "multipliers": 0.5 },
            { "attackerType": "dragon",   "multipliers": 1 },
            { "attackerType": "dark",     "multipliers": 1 },
            { "attackerType": "fairy",    "multipliers": 1 }
        ]
    },
    {
        "defenderType": "dragon",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 1 },
            { "attackerType": "fighting", "multipliers": 1 },
            { "attackerType": "flying",   "multipliers": 1 },
            { "attackerType": "poison",   "multipliers": 1 },
            { "attackerType": "ground",   "multipliers": 1 },
            { "attackerType": "rock",     "multipliers": 1 },
            { "attackerType": "bug",      "multipliers": 1 },
            { "attackerType": "ghost",    "multipliers": 1 },
            { "attackerType": "steel",    "multipliers": 1 },
            { "attackerType": "fire",     "multipliers": 0.5 },
            { "attackerType": "water",    "multipliers": 0.5 },
            { "attackerType": "grass",    "multipliers": 0.5 },
            { "attackerType": "electric", "multipliers": 0.5 },
            { "attackerType": "psychic",  "multipliers": 1 },
            { "attackerType": "ice",      "multipliers": 2 },
            { "attackerType": "dragon",   "multipliers": 2 },
            { "attackerType": "dark",     "multipliers": 1 },
            { "attackerType": "fairy",    "multipliers": 2 }
        ]
    },
    {
        "defenderType": "dark",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 1 },
            { "attackerType": "fighting", "multipliers": 2 },
            { "attackerType": "flying",   "multipliers": 1 },
            { "attackerType": "poison",   "multipliers": 1 },
            { "attackerType": "ground",   "multipliers": 1 },
            { "attackerType": "rock",     "multipliers": 1 },
            { "attackerType": "bug",      "multipliers": 2 },
            { "attackerType": "ghost",    "multipliers": 0.5 },
            { "attackerType": "steel",    "multipliers": 1 },
            { "attackerType": "fire",     "multipliers": 1 },
            { "attackerType": "water",    "multipliers": 1 },
            { "attackerType": "grass",    "multipliers": 1 },
            { "attackerType": "electric", "multipliers": 1 },
            { "attackerType": "psychic",  "multipliers": 0 },
            { "attackerType": "ice",      "multipliers": 1 },
            { "attackerType": "dragon",   "multipliers": 1 },
            { "attackerType": "dark",     "multipliers": 0.5 },
            { "attackerType": "fairy",    "multipliers": 2 }
        ]
    },
    {
        "defenderType": "fairy",
        "attackerFactors": [
            { "attackerType": "normal",   "multipliers": 1 },
            { "attackerType": "fighting", "multipliers": 0.5 },
            { "attackerType": "flying",   "multipliers": 1 },
            { "attackerType": "poison",   "multipliers": 2 },
            { "attackerType": "ground",   "multipliers": 1 },
            { "attackerType": "rock",     "multipliers": 1 },
            { "attackerType": "bug",      "multipliers": 0.5 },
            { "attackerType": "ghost",    "multipliers": 1 },
            { "attackerType": "steel",    "multipliers": 2 },
            { "attackerType": "fire",     "multipliers": 1 },
            { "attackerType": "water",    "multipliers": 1 },
            { "attackerType": "grass",    "multipliers": 1 },
            { "attackerType": "electric", "multipliers": 1 },
            { "attackerType": "psychic",  "multipliers": 1 },
            { "attackerType": "ice",      "multipliers": 1 },
            { "attackerType": "dragon",   "multipliers": 0 },
            { "attackerType": "dark",     "multipliers": 0.5 },
            { "attackerType": "fairy",    "multipliers": 1 }
        ]
    }
]
